server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #表示不向注册中心注册自己
    fetch-registry: true #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # 集群版
#      defaultZone: http://localhost:7001/eureka/ # 不搭建集群 单机 指向自己

