server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# feign是集成了hystrix的，通过设置打开对Hystrix的支持
feign:
  hystrix:
    enabled: true

# 下面的代码设置超时调用
#feign:
#  httpclient:
#    enabled: true
#    connection-timeout: 60000
#  client:
#    config:
#      default:
#        connectTimeout: 60000
#        readTimeout: 60000
#        loggerLevel: FULL
#ribbon:
#  ConnectTimeout: 60000
#  ReadTimeout: 60000